# Default values for aks-store-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: "dev"

aiService:
  # Specifies whether a ai-service deployment and service should be created
  create: false
  modelDeploymentName: ""
  openAiEndpoint: ""
  openAiKey: ""
  openAiOrgId: ""
  managedIdentityClientId: ""
  useAzureOpenAi: false
  useAzureAd: false
  image:
    repository: "ghcr.io/azure-samples/aks-store-demo/ai-service"
    tag: "latest"

orderService:
  useAzureServiceBus: false # when false, local rabbitmq will be used
  queueHost: "rabbitmq"
  queuePort: "5672"
  queueUsername: "username"
  queuePassword: "password"
  queueName: "orders"
  queueTransport: ""
  image:
    repository: "ghcr.io/azure-samples/aks-store-demo/order-service"
    tag: "latest"

makelineService:
  useAzureCosmosDB: false # when false, local mongodb will be used
  useSqlApi: false # when false, mongodb api for azure cosmosdb will be used
  orderQueueUri: "amqp://rabbitmq:5672"
  orderQueueUsername: "username"
  orderQueuePassword: "password"
  orderQueueName: "orders"
  orderDBUri: "mongodb://mongodb:27017"
  orderDBName: "orderdb"
  orderDBCollectionName: "orders"
  orderDBContainerName: "orders"
  orderDBUsername: ""
  orderDBPassword: ""
  image:
    repository: "ghcr.io/azure-samples/aks-store-demo/makeline-service"
    tag: "latest"

productService:
  image:
    repository: "ghcr.io/azure-samples/aks-store-demo/product-service"
    tag: "latest"

storeAdmin:
  image:
    repository: "ghcr.io/azure-samples/aks-store-demo/store-admin"
    tag: "latest"
  serviceType: LoadBalancer

storeFront:
  image:
    repository: "ghcr.io/azure-samples/aks-store-demo/store-front"
    tag: "latest"
  serviceType: LoadBalancer

virtualCustomer:
  image:
    repository: "ghcr.io/azure-samples/aks-store-demo/virtual-customer"
    tag: "latest"

virtualWorker:
  image:
    repository: "ghcr.io/azure-samples/aks-store-demo/virtual-worker"
    tag: "latest"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}